# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  matheussesstarwarswebapi:
    image: matheussesstarwarswebapi
    build:
      context: .
      dockerfile: src/Matheusses.StarWars.WebApi/Dockerfile
    ports:
      - 5280:5280
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
