name: report-test

on: [push]

env:
  PATH_TESTS_PROJECT: ./src/Matheusses.StarWars.UnitTest/Matheusses.StarWars.UnitTest.csproj
  NUGET_SERVER: https://api.nuget.org/v3/index.json
  TEST_DIRECTORY: ./src/Matheusses.StarWars.UnitTest

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Show pre-existing .NET installations
      run: |
        dotnet --list-sdks
        echo '**** Default version for .NET ****'
        dotnet --version

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.102

    - name: Display default version after installing .NET 7
      run: dotnet --version

    - name: Test Execution 
      run: dotnet test ${{ env.PATH_TESTS_PROJECT }} --verbosity minimal --logger:"html;LogFileName=report-test.html" --collect:"XPlat Code Coverage"
      if: always()

    - name: Install ReportGenerator
      if: success()
      run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.8.4

    - name: Generate report cover tests with ReportGenerator
      if: success()
      run: |
        cd ${{ env.TEST_DIRECTORY }}/TestResults
        # Access directory generate with the cover code XML
        cd $(ls -d */|head -n 1)
        reportgenerator "-reports:coverage.cobertura.xml" "-targetdir:coveragereport" -reporttypes:Html

    - name: Upload report cover code success as an artifact
      uses: actions/upload-artifact@v2.2.2
      env:
        PATH_RESULT_TEST: ${{ env.TEST_DIRECTORY }}/TestResults/
      if: success()
      with:
        name: result-test
        path: ${{ env.PATH_RESULT_TEST }}
        retention-days: 30

    - name: Upload report cover code with fails as an artifact
      uses: actions/upload-artifact@v2.2.2
      if: failure()
      env:
        PATH_FAIL_REPORT: ${{ env.TEST_DIRECTORY }}/TestResults/report-test.html
      with:
        name: fail-test-result
        path: ${{ env.PATH_FAIL_REPORT }}
        retention-days: 30        
